spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://git.netcracker.com/tema0922/cloud-config-server.git
          force-pull: true
          username: tema0922
          password: June@2023
          default-label: master

server:
  port: 8092

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/